# Generated by Django 3.0.2 on 2020-08-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200805_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
