# Generated by Django 3.0.2 on 2020-08-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_posts_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
